services:
  mysql:
    image: mysql:8.0
    container_name: cgv-mysql
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cgv_streaming
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: cgv-backend
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    environment:
      FLASK_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: cgv_streaming
    ports:
      - "5000:5000"  # External port 5000 maps to internal 5000

volumes:
  mysql_data:
