version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: web1-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cgv_streaming
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: web1-backend
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    environment:
      FLASK_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: cgv_streaming
    ports:
      - "5000:5000"
    # Uncomment to develop with live code edits (bind mount)
    # volumes:
    #   - .:/app

volumes:
  mysql_data:
